[package]
name = "iota-network"
version = "0.0.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
dashmap.workspace = true
governor.workspace = true
serde.workspace = true
shared-crypto.workspace = true
tonic.workspace = true
tower.workspace = true

iota-archival.workspace = true
iota-config.workspace = true
iota-macros.workspace = true
iota-protocol-config.workspace = true
iota-simulator.workspace = true
iota-storage.workspace = true
iota-swarm-config.workspace = true
iota-types.workspace = true

anyhow.workspace = true
arc-swap.workspace = true
bcs.workspace = true
bytes.workspace = true
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
futures.workspace = true
iota-common.workspace = true
iota-metrics.workspace = true
iota-network-stack.workspace = true
prometheus.workspace = true
rand.workspace = true
tap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[build-dependencies]
anemo-build.workspace = true
tonic-build.workspace = true

[dev-dependencies]
ed25519-consensus.workspace = true
iota-macros.workspace = true
telemetry-subscribers.workspace = true
tempfile = "3.3.0"
tokio = { workspace = true, features = ["test-util"] }
