[package]
name = "iota-move-natives-v2"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move framework for iota platform"

[dependencies]
bcs.workspace = true
better_any.workspace = true
indexmap.workspace = true
smallvec.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true

move-stdlib-natives = { path = "../../../external-crates/move/move-execution/v2/crates/move-stdlib-natives", package = "move-stdlib-natives-v2" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-runtime", package = "move-vm-runtime-v2" }
move-vm-types = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-types", package = "move-vm-types-v2" }

iota-protocol-config.workspace = true
iota-types.workspace = true
tracing.workspace = true
