[package]
name = "iota-oracle"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
bcs.workspace = true
chrono.workspace = true
clap.workspace = true
jsonpath_lib = "0.3.0"
once_cell.workspace = true
prometheus = "0.13.3"
reqwest.workspace = true
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = { version = "1.0.1" }
tap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.36"

iota-config.workspace = true
iota-json-rpc-types.workspace = true
iota-metrics.workspace = true
iota-sdk.workspace = true
iota-types.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
bcs = "0.1.5"
dirs = "4.0.0"
iota-keys.workspace = true
iota-move-build.workspace = true
rand = "0.8.5"
shared-crypto.workspace = true
