[package]
name = "iota-adapter-transactional-tests"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Transactional tests for IOTA Adapter"

[dev-dependencies]
datatest-stable.workspace = true
iota-transactional-test-runner.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
