[package]
name = "iota-verifier-transactional-tests"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
description = "Transactional tests for IOTA Verifier"
license = "Apache-2.0"
publish = false
edition = "2021"

[dev-dependencies]
datatest-stable.workspace = true
iota-transactional-test-runner.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]

