edition = "2021"
style_edition = "2024"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
ignore = [
  "crates/iota-indexer-alt-jsonrpc/src/api/coin.rs",
  "crates/iota-indexer-alt-jsonrpc/src/api/write.rs",
  "crates/iota-indexer-alt-jsonrpc/src/api/objects.rs",
  "crates/iota-indexer-alt-jsonrpc/src/api/transactions/mod.rs",
  "crates/iota-json-rpc-api/src/coin.rs",
  "crates/iota-json-rpc-api/src/extended.rs",
  "crates/iota-json-rpc-api/src/indexer.rs",
  "crates/iota-json-rpc-api/src/read.rs",
  "crates/iota-json-rpc-api/src/transaction_builder.rs",
  "crates/iota-json-rpc-api/src/write.rs",
  "external-crates",
]
