[package]
name = "iota-node"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
arc-swap.workspace = true
axum.workspace = true
anyhow.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
consensus-core.workspace = true
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
parking_lot.workspace = true
tower.workspace = true
tower-http.workspace = true
http.workspace = true
reqwest.workspace = true
tap.workspace = true
serde.workspace = true
bin-version.workspace = true
url.workspace = true
humantime.workspace = true

iota-archival.workspace = true
iota-tls.workspace = true
iota-macros.workspace = true
iota-config.workspace = true
iota-core.workspace = true
iota-rpc-api.workspace = true
iota-storage.workspace = true
iota-name-service.workspace = true
iota-network.workspace = true
iota-json-rpc.workspace = true
iota-json-rpc-api.workspace = true
iota-protocol-config.workspace = true
iota-snapshot.workspace = true
iota-telemetry.workspace = true
iota-types.workspace = true
iota-metrics.workspace = true
iota-service.workspace = true
iota-common.workspace = true
typed-store.workspace = true
iota-network-stack.workspace = true
telemetry-subscribers.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-vm-profiler.workspace = true
iota-http.workspace = true

[target.'cfg(msim)'.dependencies]
iota-simulator.workspace = true

