// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/// A JSONRPC module implementation coupled with a description of its schema.
pub trait RpcModule: Sized {
    /// Docs to add to the schema usually generated by the `open_rpc` macro.
    fn schema(&self) -> iota_open_rpc::Module;

    /// The implementation of the JSONRPC module.
    fn into_impl(self) -> jsonrpsee::RpcModule<Self>;
}
