[package]
name = "iota-util-mem"
version = "0.11.0"
authors = [
  "Parity Technologies <admin@parity.io>",
  "Andrew Schran <aschran@iota.org>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
rust-version = "1.56.1"
description = "Collection of memory-related utilities"

[dependencies]
cfg-if.workspace = true
ed25519-consensus.workspace = true
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
hashbrown = { workspace = true, optional = true }
impl-trait-for-tuples.workspace = true
indexmap.workspace = true
iota-util-mem-derive.workspace = true
roaring.workspace = true

once_cell.workspace = true
parking_lot = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }

[features]
default = ["std", "hashbrown", "smallvec", "estimate-heapsize"]
std = ["parking_lot"]
# Full estimate: no call to allocator
estimate-heapsize = []
