[package]
name = "typed-store"
version = "0.4.0"
authors = ["Francois Garillot <francois@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
description = "a typed database interface"

[dependencies]
async-trait.workspace = true
bcs.workspace = true
bincode.workspace = true
collectable.workspace = true
eyre.workspace = true
fdlimit.workspace = true
hdrhistogram.workspace = true
iota-macros.workspace = true
itertools.workspace = true
once_cell.workspace = true
prometheus.workspace = true
rand.workspace = true
rocksdb = { version = "0.21.0", default-features = false, features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"] }
serde.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
tracing.workspace = true
typed-store-derive = { path = "../typed-store-derive" }
typed-store-error.workspace = true
typed-store-workspace-hack = { path = "../typed-store-workspace-hack" }

[dev-dependencies]
once_cell.workspace = true
rand.workspace = true
rstest.workspace = true
tempfile.workspace = true
uint.workspace = true

# Most packages should depend on iota-simulator instead of directly on msim, but for typed-store
# that creates a circular dependency.
[target.'cfg(msim)'.dependencies]
msim.workspace = true
