[package]
name = "move-vm-runtime-v0"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Core Move execution logic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better_any.workspace = true
fail.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-bytecode-verifier = { path = "../move-bytecode-verifier", package = "move-bytecode-verifier-v0" }
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-profiler.workspace = true
move-vm-types = { path = "../move-vm-types", package = "move-vm-types-v0" }

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
move-compiler.workspace = true
move-ir-compiler.workspace = true
proptest.workspace = true

[features]
default = []
fuzzing = ["move-vm-types/fuzzing"]
failpoints = ["fail/failpoints"]
# Enable tracing and debugging also for release builds. By default, it is only enabled for debug builds.
debugging = []
testing = []
lazy_natives = []
tracing = [
  "move-vm-config/tracing",
  "move-vm-profiler/tracing",
]
