[package]
name = "iota-indexer-alt-schema"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
diesel = {workspace = true, features = ["postgres_backend", "chrono"]}
diesel_migrations.workspace = true
serde.workspace = true
bcs.workspace = true

iota-field-count.workspace = true
iota-protocol-config.workspace = true
iota-types.workspace = true

