[package]
name = "iota-display"
version.workspace = true
authors = ["IOTA Foundation <build@iota.org"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true

move-core-types.workspace = true

iota-json-rpc-types.workspace = true
iota-types.workspace = true

