[package]
name = "iota-adapter-v2"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
description = "Adapter and accompanying CLI for local iota development"
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
tracing.workspace = true
serde.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/v2/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v2" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-runtime", package = "move-vm-runtime-v2" }
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
iota-move-natives = { path = "../iota-move-natives", package = "iota-move-natives-v2" }
iota-verifier = { path = "../iota-verifier", package = "iota-verifier-v2" }
move-vm-types = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-types", package = "move-vm-types-v2" }

iota-macros.workspace = true
iota-protocol-config.workspace = true
iota-types.workspace = true
parking_lot.workspace = true

[features]
tracing = [
    "iota-types/tracing",
    "move-vm-runtime/tracing",
    "move-vm-profiler/tracing",
    "move-vm-config/tracing",
]

