[package]
name = "iota-adapter-v0"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Adapter and accompanying CLI for local iota development"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
once_cell.workspace = true
serde.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-profiler.workspace = true

iota-move-natives = { path = "../iota-move-natives", package = "iota-move-natives-v0" }
iota-verifier = { path = "../iota-verifier", package = "iota-verifier-v0" }
move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/v0/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v0" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v0/crates/move-vm-runtime", package = "move-vm-runtime-v0" }
move-vm-types = { path = "../../../external-crates/move/move-execution/v0/crates/move-vm-types", package = "move-vm-types-v0" }

iota-macros.workspace = true
iota-protocol-config.workspace = true
iota-types.workspace = true
parking_lot.workspace = true

[dev-dependencies]
move-package.workspace = true

[features]
tracing = [
  "iota-types/tracing",
  "move-vm-runtime/tracing",
  "move-vm-profiler/tracing",
  "move-vm-config/tracing",
]
