[package]
name = "iota-archival"
version.workspace = true
edition = "2021"
publish = false
license = "Apache-2.0"
authors = ["IOTA Foundation <info@iota.org>"]

[dependencies]
indicatif.workspace = true
anyhow.workspace = true
serde.workspace = true
byteorder.workspace = true
tracing.workspace = true
bytes.workspace = true
num_enum.workspace = true
futures.workspace = true
rand.workspace = true
object_store.workspace = true
prometheus.workspace = true
iota-config.workspace = true
iota-types.workspace = true
iota-storage.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
tokio = { workspace = true, features = ["full"] }
serde_json = "1.0.95"

[dev-dependencies]
tempfile.workspace = true
more-asserts.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
tokio = { workspace = true, features = ["test-util"] }
ed25519-consensus.workspace = true
fastcrypto.workspace = true
iota-swarm-config.workspace = true
iota-macros.workspace = true

[target.'cfg(msim)'.dependencies]
iota-simulator.workspace = true

