[package]
name = "iota-indexer-alt-framework"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bb8 = "0.8.5"
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
diesel_migrations.workspace = true
futures.workspace = true
prometheus.workspace = true
reqwest.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }
url.workspace = true

iota-field-count.workspace = true
iota-indexer-alt-metrics.workspace = true
iota-pg-db.workspace = true
iota-sql-macro.workspace = true
iota-storage.workspace = true
iota-types.workspace = true
iota-rpc-api.workspace = true
tonic.workspace = true

[dev-dependencies]
rand.workspace = true
telemetry-subscribers.workspace = true
wiremock.workspace = true

iota-synthetic-ingestion.workspace = true

[features]
default = ["cluster"]
cluster = ["dep:tracing-subscriber"]

