[package]
name = "iota-rpc-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
axum = { workspace = true, features = ["matched-path"] }
base64.workspace = true
bcs.workspace = true
http.workspace = true
iota-sdk-transaction-builder.workspace = true
iota-sdk-types.workspace = true
itertools.workspace = true
mime = "0.3.17"
prometheus.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower.workspace = true
tracing.workspace = true
url.workspace = true

fastcrypto.workspace = true
iota-network-stack.workspace = true
iota-protocol-config.workspace = true
iota-types.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true

# dependencies for the protobuf definitions
bytes.workspace = true
prost.workspace = true
prost-types = "0.13.3"
roaring.workspace = true
tonic.workspace = true

tonic-health.workspace = true
tonic-reflection.workspace = true

[dev-dependencies]
iota-sdk-types = { workspace = true, features = ["proptest"] }
paste = "1.0.15"
proptest.workspace = true
protox = "0.7"
test-strategy = "0.4.0"
tonic-build = "0.12.3"
walkdir.workspace = true
