[package]
name = "iota-proc-macros"
version = "0.7.0"
authors = ["IOTA Foundation <info@iota.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { version = "2", features = ["full", "fold", "extra-traits"] }
proc-macro2.workspace = true
iota-enum-compat-util.workspace = true

[target.'cfg(msim)'.dependencies]
msim-macros.workspace = true

