name: Changesets

on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    runs-on: self-hosted-x64
    steps:
      - name: checkout code repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # v1.4.5
        with:
          # Generates src/version.ts file using genVersion
          # https://github.com/changesets/action#with-version-script
          version: pnpm changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
