[package]
name = "move-stackless-bytecode"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Move stackless bytecode"

[dependencies]
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-model.workspace = true

codespan.workspace = true
codespan-reporting = { workspace = true, features = ["serde", "serialization"] }
ethnum.workspace = true
im.workspace = true
itertools.workspace = true
log.workspace = true
num.workspace = true
petgraph.workspace = true
serde.workspace = true

[dev-dependencies]
anyhow.workspace = true
datatest-stable.workspace = true
move-stdlib.workspace = true
regex.workspace = true

[[test]]
name = "testsuite"
harness = false
